USE biblioteca;

INSERT INTO libros (titulo, autor, genero, anio) VALUES
('1984', 'George Orwell', 'Distopía', 1949),
('Cien años de soledad', 'Gabriel García Márquez', 'Realismo mágico', 1967),
('Don Quijote de la Mancha', 'Miguel de Cervantes', 'Novela', 1605),
('Matar a un ruiseñor', 'Harper Lee', 'Ficción', 1960),
('Orgullo y prejuicio', 'Jane Austen', 'Romance', 1813),
('El gran Gatsby', 'F. Scott Fitzgerald', 'Ficción', 1925),
('Crimen y castigo', 'Fiódor Dostoyevski', 'Ficción', 1866),
('En busca del tiempo perdido', 'Marcel Proust', 'Ficción', 1913),
('Ulises', 'James Joyce', 'Ficción', 1922),
('La Odisea', 'Homero', 'Épica', -800),
('La Ilíada', 'Homero', 'Épica', -750),
('El señor de los anillos', 'J.R.R. Tolkien', 'Fantasía', 1954),
('El hobbit', 'J.R.R. Tolkien', 'Fantasía', 1937),
('Fahrenheit 451', 'Ray Bradbury', 'Ciencia ficción', 1953),
('El guardián entre el centeno', 'J.D. Salinger', 'Ficción', 1951),
('El nombre de la rosa', 'Umberto Eco', 'Misterio', 1980),
('La metamorfosis', 'Franz Kafka', 'Ficción', 1915),
('El extranjero', 'Albert Camus', 'Ficción', 1942),
('El principito', 'Antoine de Saint-Exupéry', 'Ficción', 1943),
('Cumbres borrascosas', 'Emily Brontë', 'Romance', 1847),
('Drácula', 'Bram Stoker', 'Horror', 1897),
('Frankenstein', 'Mary Shelley', 'Horror', 1818),
('El retrato de Dorian Gray', 'Oscar Wilde', 'Ficción', 1890),
('Los miserables', 'Victor Hugo', 'Ficción', 1862),
('La divina comedia', 'Dante Alighieri', 'Épica', 1320),
('El código Da Vinci', 'Dan Brown', 'Misterio', 2003),
('El alquimista', 'Paulo Coelho', 'Ficción', 1988),
('La sombra del viento', 'Carlos Ruiz Zafón', 'Misterio', 2001),
('El amor en los tiempos del cólera', 'Gabriel García Márquez', 'Romance', 1985),
('La casa de los espíritus', 'Isabel Allende', 'Realismo mágico', 1982),
('El perfume', 'Patrick Süskind', 'Ficción', 1985),
('La insoportable levedad del ser', 'Milan Kundera', 'Ficción', 1984),
('El viejo y el mar', 'Ernest Hemingway', 'Ficción', 1952),
('El lobo estepario', 'Hermann Hesse', 'Ficción', 1927),
('Siddhartha', 'Hermann Hesse', 'Ficción', 1922),
('El proceso', 'Franz Kafka', 'Ficción', 1925),
('La montaña mágica', 'Thomas Mann', 'Ficción', 1924),
('El ruido y la furia', 'William Faulkner', 'Ficción', 1929),
('Moby Dick', 'Herman Melville', 'Aventura', 1851),
('La isla del tesoro', 'Robert Louis Stevenson', 'Aventura', 1883),
('Robinson Crusoe', 'Daniel Defoe', 'Aventura', 1719),
('Las aventuras de Tom Sawyer', 'Mark Twain', 'Aventura', 1876),
('Las aventuras de Huckleberry Finn', 'Mark Twain', 'Aventura', 1884),
('El conde de Montecristo', 'Alexandre Dumas', 'Aventura', 1844),
('Veinte mil leguas de viaje submarino', 'Julio Verne', 'Ciencia ficción', 1870),
('La vuelta al mundo en ochenta días', 'Julio Verne', 'Aventura', 1873),
('Viaje al centro de la Tierra', 'Julio Verne', 'Ciencia ficción', 1864),
('El hombre invisible', 'H.G. Wells', 'Ciencia ficción', 1897),
('La guerra de los mundos', 'H.G. Wells', 'Ciencia ficción', 1898);